### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by wooleee** [KeondoPark/coral_mask#1]
detect_mask2.py 실행시 아래의 오류가 나타납니다.

이전에 interpreter2의 텐서를 불러올 때 에러가 나서, 

아래 부분을 
Interpreter2 = tflite.Interpreter(model_path = args.model2)

아래와 같이 바꾸었습니다.
Interpreter2 = tflite.Interpreter(model_path = args.model2, experimental_dell
egates=[tflite.load_delegate('libedgetpu.so.1')])

그 이후 모델이 실행이 되는 것은 확인했는데,
코드를 하나도 바꾸지 않고 실행했음에도 timeout error가 발생합니다.

원인찾아볼게요.

**<에러 메세지>**

select timeout
select timeout
OpenCV Error: Assertion failed (total() == 0 || data != NULL) in Mat, file /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/core/include/opencv2/core/mat.inl.hpp, line 431
Traceback (most recent call last):
  File "detect_mask2.py", line 225, in <module>
    main()
  File "detect_mask2.py", line 129, in main
    ret, frame = cap.read()
cv2.error: /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/core/include/opencv2/core/mat.inl.hpp:431: error: (-215) total() == 0 || data != NULL in function Mat

**Comment by KeondoPark** [comment]
Does it happen on Coral? or on your laptop?
You should use common.make_interpreter to run on Coral.(It is commented now)
Please see below to find the default code for Coral, before I modified.
https://github.com/google-coral/examples-camera/tree/master/opencv

**Comment by wooleee** [comment]
handled and solved. Best.
